INSERT INTO categories (name)
VALUES
    ('Income'),
    ('Transfers'),
    ('Savings'),
    ('Rent / Mortgage'),
    ('Utilities'),
    ('Insurance'),
    ('Groceries'),
    ('Eating out'),
    ('Transport'),
    ('Car'),
    ('Dog'),
    ('Health'),
    ('Subscriptions'),
    ('Shopping'),
    ('Household'),
    ('Entertainment'),
    ('Travel'),
    ('Gifts'),
    ('Taxes'),
    ('Fees'),
    ('One-off / Large purchase'),
    ('Unknown')
ON CONFLICT (name) DO NOTHING;
